### ISSUE TITLE
Feature Request: add Kanban-yaml to metadata

### ISSUE THREAD

**Issue by chrisgrieser** [kometenstaub/metadata-extractor#12]
if you could add the presence of this yaml key to the metadata, Alfred could detect whether a note is a kanban board or note. This would enable various features, like for example adding cards to Kanbans via Alfred.

```yaml
---
kanban-plugin: basic
---
```

**Comment by kometenstaub** [comment]
See #6 and #11.

**Comment by kometenstaub** [comment]
The frontmatter is exported now.
