### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by msageryd** [kometenstaub/metadata-extractor#25]
### This seems to be a very nice plugin!
I have tried numerous ways to access Obsidian from Alfred. Since Obsidian is quite stubborn with it's x-callback interface it's hard to query Obsidian without changing focus to Obsidian.

### I have tried some approaches:
- Omnisearch exposes an http interface, but this is of course limited to just the search function
- I added an http interface to the obsidian-actions-uri plugin (in a fork). This works ok, but I still face some x-callback issues

Actions-uri plugin with added http interface: https://github.com/msageryd/obsidian-actions-uri

### I have some questions on metadata-extractor:
- Did you consider using an SQLlite database instead of JSON files?
- Obsidian seems to provide hooks for most changes, why didn't you opt to use these instead of intervals for writing metadata?
- The writing of metadata seems to always write everything. I might have misunderstood, though. If I'm right, why didn't you opt for writing only chnaged data?

N.B. This is not meant as criticism. It's a really nice project. I'm just wondering if there are any culprits which made you to not implement any of the features in the above questions.

### My dream setup would be:
1. write metadata to SQLlite database
2. also include the actual note data for better searchability
3. write metadata on every change based on Obsidian hooks
4. fork the hands down best Alfred workflow for Bear Notes and make it work with the Obsidian SQlLite database.

The Alfred workflow I'm refering to is this: https://github.com/drgrib/alfred-bear
The core of this plugin is a Go program which interacts directly with Bear's SQLlite database.

**Comment by kometenstaub** [comment]
> Did you consider using an SQLlite database instead of JSON files?

I did not. This project was (and mainly is) intended for use with this workflow: https://github.com/chrisgrieser/shimmering-obsidian

JSON is easily readable with JXA without dependencies, which is what the author used/uses.

> Obsidian seems to provide hooks for most changes, why didn't you opt to use these instead of intervals for writing metadata?

I'm not sure. As this was my first Obsidian plugin and at the time, there was no documentation besides a (lot less annotated) `d.ts` file, I might not have been aware of that possibility. I'm also not sure whether it would be a good idea with JSON files, depending on how often metadata updates.
It might have been a trade-off between complexity and what “just worked”.

> The writing of metadata seems to always write everything. I might have misunderstood, though. If I'm right, why didn't you opt for writing only changed data?

It makes the plugin less complex.
Honestly, the plugin could need a rewrite. As it was my first bigger coding project and API documentation didn't exist, I either wasn't aware of some APIs or some got added later on which would simplify things, and code quality could generally be improved.

**Comment by msageryd** [comment]
Thank you for your reply.
I have now dug quite deep into this and concluded that it's really hard to do it any other way than you did.

Every SQLLite library I have tried has some troubles in Obsidian. The native lib has to be rebuilt for each Electron version, which would be a PITA for a plugin. Also, I couldn't get the JS based SQL Lite library running due to some webAsm problem. It would be really hard to maintain such a plugin, even if I could get an SQL Lite library to work

Another aproach, which might scale better than your "rewrite-everything" approach, would be to write changes to a change-log, by just appending to a text file. An external program could then parse the change-log and make the changes in an SQL Lite database. This introduces more moving parts and would also be hard to maintain.

I'm actually quite bummed by all the trouble I'm getting with Obsidians Electron environment. As of now I'm almost prepared to migrate back to Bear. At the very least I will revisit my reviewing of alternatives (LogSeq, AnyType, etc)

I just wanted to let you know..
//Michael

**Comment by kometenstaub** [comment]
> Another aproach, which might scale better than your "rewrite-everything" approach, would be to write changes to a change-log, by just appending to a text file.

At that point it seems to me that writing a custom metadata extraction program working directly on the files would make more sense.

**Comment by msageryd** [comment]
> At that point it seems to me that writing a custom metadata extraction program working directly on the files would make more sense.

Yes, and that does not seem to be a good idea. It would be like building a mini-obsidian on the side.

I gave it one more chance. Managed to import and use sql.js from within Obsidian. But then it dawned on me that the wasm-version can only work with a memory database. I'd have to write the complete database to disk everytime, which would be the same as your solution in terms of scalability.

The only way to work directly with an SQL Lite file on disk is to use a compiled native version of the SQLLite lib, which seems to be a PITA in Obsidian, if even possible.

I give up on this for now..

Thanks again for your feedback.

**Comment by kometenstaub** [comment]
In case this helps, at least for macOS there seems to be a command line utility you could use:

https://github.com/liamcain/obsidian-things-logbook/blob/main/src/sqlite.ts

**Comment by msageryd** [comment]
Haha, you just repoened the case for me.. 
I had just got rid of it, but this opens up new possibilities, so I'm not off the hook =)

Thank you, I didn't know that this existed. Aparently sqlite3 is preinstalled in MacOs and most Linux distros. On Windows you can install it, but that't not a concern to me since the whole purpose is an Alfred Workflow, i.e. only Mac.

**Comment by msageryd** [comment]
Wow, this went smoothly. Thank you for your heads up! 

I now have a realtime synked sqlite database including tags and frontmeta. I'll have to figure out how to detect changes when those arrive from synced devices.

I don't mean to take your time with this feedback. Just thought you might be interested.

**Comment by kometenstaub** [comment]
> I'll have to figure out how to detect changes when those arrive from synced devices.

While it should be possible to access Sync events via the private undocumented API, it makes more sense to watch for metadata cache changes. I haven't worked with it in this circumstance, but a changed event (or something similar) should get fired when the cache gets updated upon receiving an update.


> I don't mean to take your time with this feedback. Just thought you might be interested.

I appreciate it! I‘m glad my idea worked out.

**Comment by msageryd** [comment]
FYI, upon arrival of altered files via sync (in my case via iCloud), all the regular events are triggered (i.e. modify, create, delete, rename), so no special handling is needed for sync.

If you are curious.
https://github.com/msageryd/obsidian-sqlite-sync

The plugin works fine. Some tweaks might be needed, but for now I'm happy. Now moving on to port the Go library for the Alfred workflow
